version: "3"
services:
  react-app:
    image: react-app
    build: ./front/
    stdin_open: true
    ports: 
      - "3000:3000"
    networks:
      - mern-app
    volumes:
      - ./front:/usr/src/app 
      - /usr/src/app/node_modules

  api-server:
    image: api-server
    build: ./back/
    ports: 
      - "5000:5000"
    networks: 
      - mern-app
    volumes:
      - ./back:/usr/src/app 
      - /usr/src/app/node_modules
    depends_on: 
      - mongo

  mongo:
    image: mongo:4.4-bionic
    ports: 
      - "27017:27017"
    networks: 
      - mern-app
    volumes: 
      - mongo-data:/data/db

networks:
  mern-app:
    driver: bridge

volumes:
  mongo-data:
    driver: local